export default {
	UPDATE_IMAGE: "UPDATE_IMAGE",
	TOGGLE_MODAL: "TOGGLE_MODAL",
	UPDATE_CROPPED_IMAGE: "UPDATE_CROPPED_IMAGE",
	UPDATE_THEME: "UPDATE_THEME",
	UPDATE_BACKDROP: "UPDATE_BACKDROP",
	UPDATE_SECRET_QUESTION: "UPDATE_SECRET_QUESTION",
	UPDATE_PERSONALIZATION_DETAILS: "UPDATE_PERSONALIZATION_DETAILS",
	UPDATE_PERSONALIZATION_SUCCESS: "UPDATE_PERSONALIZATION_SUCCESS",
	SHOW_SAFETY_TIPS: "SHOW_SAFETY_TIPS",
	ADD_NOTIFICATION: "ADD_NOTIFICATION",
	UPDATE_ERROR: "UPDATE_ERROR",
	REMOVE_NOTIFICATION: "REMOVE_NOTIFICATION",
	RESET_STORE: "RESET_STORE"
};