export default {
	getTokens: "mocks/getToken/index.json",
	checkUser: "mocks/checkUser/index.json",
	authenticate: "mocks/authenticate/index.json",
	getRegistrationDetails: "mocks/getRegistrationDetails/index.json",
	asyncAuthenticatePin: "mocks/asyncAuthenticatePin/index.json",
	getPersonalizationDetails: "mocks/getPersonalizationDetails/index.json",
	getDashboardData: "mocks/getDashboardData/index.json",
	getAsyncLogoutData: "mocks/getAsyncLogoutData/index.json",
	getFixedDepositCardDetails: "mocks/getFixedDepositCardDetails/index.json",
	getJointFixedDepositCardDetails: "mocks/getJointFixedDepositCardDetails/index.json",
	getCardAccountDetails: "mocks/getCardAccountDetails/index.json",
	getCasaAccountDetails: "mocks/getCasaAccountDetails/index.json",
	getCasaSavingsAccountDetails: "mocks/getCasaSavingsAccountDetails/index.json",
	getCasaCurrentAccountDetails: "mocks/getCasaCurrentAccountDetails/index.json",
	getLoanCardDetails: "mocks/getLoanCardDetails/index.json",
	getHirePurchaseDetails: "mocks/getHirePurchaseDetails/index.json",
	getTermLoanDetails: "mocks/getTermLoanDetails/index.json",
	getIslamicTermLoans: "mocks/getIslamicTermLoans/index.json",
	getAsbFinancingDetails: "mocks/getAsbFinancingDetails/index.json",
	getProgressiveInterestDetails: "mocks/getProgressiveInterestDetails/index.json",
	getRewardCardDetails: "mocks/getRewardCardDetails/index.json",
	getInboxData: "mocks/getInboxData/index.json",
	getAsyncPayeeList: "mocks/PayAPI/getPayeeList/index.json",
	getAsyncPayDetails: "mocks/PayAPI/getPayDetails/index.json",
	getAsyncFavorites: "mocks/PayAPI/getFavorites/index.json",
	getAsyncJomPayBiller: "mocks/PayAPI/getJomPayBiller/index.json",
	getFDCertificateSummary: "mocks/getFDCertificateSummary/index.json",
	getRedrawSummary: "mocks/getRedrawSummary/index.json",
	getRedrawSuccessSummary:"mocks/getRedrawSuccessSummary/index.json",
	getFDCertificateSuccessSummary:"mocks/getFDCertificateSuccessSummary/index.json",
	getQuickPaySummary:"mocks/getQuickPaySummary/index.json",
	getQuickPaySuccessSummary:"mocks/getQuickPaySuccessSummary/index.json",
	getAsyncLoanTransfer:"mocks/getAsyncLoanTransfer/index.json",
	getCardTransfer: "mocks/getCardTransfer/index.json",
	getQuickReload: "mocks/getQuickReload/index.json",
	getQuickPayJompayDetails: "mocks/getQuickPayJompayDetails/index.json",
	getQuickPayDetails: "mocks/getQuickPayDetails/index.json",
	getQuickTransferMobileOpen: "mocks/getQuickTransferMobileOpen/index.json",
	getQuickTransferThirdPartyFav: "mocks/getQuickTransferThirdPartyFav/index.json",
	getPrepaidCardDetails: "mocks/getPrepaidCardDetails/index.json",
	getChargeCardDetails: "mocks/getChargeCardDetails/index.json",
	getOTC:"mocks/getOTC/index.json",
	getSharesInvestmentDetails:"mocks/getSharesInvestmentDetails/index.json",
	getAsyncTransferDetails: "mocks/TransferAPI/getTransferDetails/index.json",
	getAsyncTransferList: "mocks/TransferAPI/getMobileTransferInfo/index.json",
	getAsyncReloadDetails: "mocks/ReloadAPI/getReloadDetails/index.json",
	getAsyncReloadList:"mocks/ReloadAPI/getTelcoList/index.json",
	getAccumulatedAmount:"mocks/getAccumulatedAmount/index.json",
	getFavoriteSummary: "mocks/getFavoriteSummary/index.json",
	getUnitTrustDetails:"mocks/getUnitTrustDetails/index.json",
	getAccSummary:"mocks/getAccSummary/index.json",
	getQuickLink:"mocks/getQuickLink/index.json",
	getPersonalMsg:"mocks/getPersonalMsg/index.json",
	getAccSummaryMore:"mocks/getAccSummaryMore/index.json",
	getAccTransaction:"mocks/getAccTransaction/index.json",
	getGoalsMore:"mocks/getGoalsMore/index.json",
	getAccTransactionMore:"mocks/getAccTransactionMore/index.json"
};