export default 	{
	DASHBOARD_DETAILS:"DASHBOARD_DETAILS",
	WEALTH_DETAILS_SIDEBAR_TOGGLE:"WEALTH_DETAILS_SIDEBAR_TOGGLE",
	WEALTH_DETAILS_LEFT_SIDEBAR_TOGGLE:"WEALTH_DETAILS_LEFT_SIDEBAR_TOGGLE",
	RESET_WEALTH_ACCOUNT_DETAILS:"RESET_WEALTH_ACCOUNT_DETAILS",
	UPDATE_WEALTH_READ_MESSAGES:"UPDATE_WEALTH_READ_MESSAGES",
	WEALTH_TOGGLE_POPUP_MENU:"WEALTH_TOGGLE_POPUP_MENU",
	WEALTH_DETAILS:"WEALTH_DETAILS",
	GET_SHARE_ACCOUNTS_DATA:"GET_SHARE_ACCOUNTS_DATA",
	UPDATE_WEALTH_TABLE_RECORDS:"UPDATE_WEALTH_TABLE_RECORDS",
	TOGGLE_DISPLAYED_WEALTHS : "TOGGLE_DISPLAYED_WEALTHS",
	GET_SLIDER_POSITION:"GET_SLIDER_POSITION"
};