export default {
	GET_TOKENS: "GET_TOKENS",
	UPDATE_REGISTRATION_DETAILS: "UPDATE_REGISTRATION_DETAILS",
	UPDATE_CARD_DETAILS: "UPDATE_CARD_DETAILS",
	UPDATE_USER_DETAILS: "UPDATE_USER_DETAILS",
	PIN_AUTHENTICATE_SUCCESS: "PIN_AUTHENTICATE_SUCCESS",
	OTP_REQUESTED: "OTP_REQUESTED",
	ADD_NOTIFICATION: "ADD_NOTIFICATION",
	UPDATE_ERROR: "UPDATE_ERROR",
	REMOVE_NOTIFICATION: "REMOVE_NOTIFICATION",
	UPDATE_PDF_PAGES: "UPDATE_PDF_PAGES",
	TOGGLE_PDF_VIEW: "TOGGLE_PDF_VIEW",
	TOGGLE_PDF_SCALE: "TOGGLE_PDF_SCALE",
	RESET_REGISTRATION: "RESET_REGISTRATION",
	UPDATE_PERSONALIZATION_DETAILS: "UPDATE_PERSONALIZATION_DETAILS"
};